### ISSUE TITLE
Improved list for authors and institutions

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#101]
Authors threshold: show first 9 and the last one
Institutions threshold: 3 lines

**Comment by nlisgo** [comment]
@chris-huggins it would be useful to chat to you about this so that I could work on a solution that would be easy to adapt for different experiments on this section?

I will focus just on the authors for now.

Would you prefer that I focused on the desktop behaviour first or the smaller view ports?
