### ISSUE TITLE
How do we display Tables?

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints-server#113]
# Description

It could be a problem with Encoda. They could have a different way render tables

# Subtasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Item 1
- [ ] Item 2
- [ ] ...

**Comment by FAtherden-eLife** [comment]
It's because they are images in the package, no? (off topic, but same with equations)

Presumably Stencila were expecting tables to be captured as tables instead of as images, as is the case for eLife content (and the same is also true of equations - expecting them as mathML/latex instead of images).

**Comment by Maelplaine** [comment]
Thanks for your comment @FAtherden-eLife 
When you say "package", do you mean BiorXiv packages?

**Comment by scottaubrey** [comment]
At the moment the biorxiv XML has tables as images. We're waiting to get the meca archives to confirm this.

**Comment by Maelplaine** [comment]
@scottaubrey Have you been able to look into the Biorxiv Mecca files? Do we know if we have the tables as images?

**Comment by scottaubrey** [comment]
@Maelplaine I haven't been able to get the one MECA archive that Biorxiv have put in the bucket yet.

**Comment by QueenKraken** [comment]
Dependant on how BioRxiv present the table; we can't convert an image into a table. Question from @discodavey if tables are shared as images can an alt tag be used? Require BioRxiv to provide data to allow investigation.

**Comment by QueenKraken** [comment]
Meca packages received and Scott was able to identify that tables are labeled as figures, so Scott has altered the displays. Short term we are good for October so will close as done.

**Comment by FAtherden-eLife** [comment]
Thanks @QueenKraken, does the solution work if there are multiple images for the table? If the table in the original PDF extends beyond one page, these will be capture as 2 (or more) images.

**Comment by FAtherden-eLife** [comment]
(Looks like it does [[example](https://epp-node-prototype.elifesciences.org/article/10.1101/2022.05.30.22275761#tbl1)])
