### ISSUE TITLE
Investigate frontend technology we want to use (inc a templating library?)

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#144]
# Description

We desire to replace the current template strings with a templating library.

This ticket is a stand-in for a team discussion / spike to investigate what library to use.

# Dod
- [x] We have a templating library selected and included as a dependency

**Comment by discodavey** [comment]
@scottaubrey Can we close this now we have decided to use Storybook and React?

**Comment by scottaubrey** [comment]
Yup
