### ISSUE TITLE
static page prototype improvements

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/enhanced-preprints-server#214]
For Dave when he is back from holiday:

Ex 1
- [x] Include peer review content at bottom of article, and include links in jump menu ([see Figma prototype](https://www.figma.com/proto/DgQuFi7BgjiVHYhmJDVllo/EPP-prototypes-1?node-id=52%3A352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=52%3A352&hotspot-hints=0&hide-ui=1))

Ex 2
- [x] Move peer review content etc. to a separate page on example 2 (not at bottom)

Ex 3
- [x] Fixed tabs when scrolling
- [x] Include jump menu in figures and peer review tabs

Ex 4
- [x] Enable/fix scrolling issues in right column
- [x] Styling of figures and peer review content in right column tabs 

All
- [x] Can we fix all examples to avoid the weird crash/timeout that seems to occur sometimes?
- [x] Table styling
- [x] Refine styling/make bold on main nav menu
- [x] Refine styling of the “Submit your research” button: size, border radius, font size etc.
- [x] Blue links in summary for the “curation labels”.

**Comment by discodavey** [comment]
@chris-huggins The two tables that are in the examples are images so cannot style

**Comment by discodavey** [comment]
@chris-huggins In example 1 you have asked for the peer review and author response to be in the jump meni but in the figma design it's not showing the border down the side. Are you wanting this to be removed as the border is on the other designs?

**Comment by chris-huggins** [comment]
No please keep the border to match the other examples if you can. I didn’t include it in Figma because it’s not possible to prototype the selected/scroll behaviour.

**Comment by discodavey** [comment]
Closing this so @chris-huggins can create new ticket for final tweaks
