### ISSUE TITLE
HTML page with all the reviewed preprint content for PDF generation

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints-server#275]
We need an HTML page with all the reviewed preprint content so that Coko can generate PDFs on the fly using Paged.js
The page should have the following:
- preprint content
- peer review material (Review summary, Reviews and Author response)
- curation labels
- badges (not yet) 

## Sub tasks
- [x] #303 
- [x] #326 
- [x] #113 
- [ ] #

**Comment by Maelplaine** [comment]
@BlueReZZ I vaguely remember Coko saying that this page shouldn't use some javascript. Is that correct?

The second question is, do we need this to be done this sprint?

**Comment by BlueReZZ** [comment]
This only needs to be the HTML as the styles etc. will be rendered by the paged.js template. You can exclude the javascript too but I think it gets ignored anyway.

Julien will begin work on our project on Tues 23rd August and his initial plan was to generate what we had using the templates he already has. Having this page available for him soon would help his investigations but we can also use the HTML we render on the two pages for his initial investigations. So this sprint would be most helpful but it can wait until next sprint if that's more convenient.

**Comment by scottaubrey** [comment]
Ordering of elements pretty much as on the main page, but with the peer reviews and author comments at the bottom after the article body.

**Comment by QueenKraken** [comment]
@scottaubrey @will-byrne to check what is broken with regards to feedback that images are not displaying

**Comment by QueenKraken** [comment]
Unsure if Coko need new HTML - will check with Ryan as we know they are working from an old HTML from the old EPP.

**Comment by QueenKraken** [comment]
Ryan has confirmed this is the list they have: https://epp-node-prototype.elifesciences.org/ Ryan believes this is the latest from BioRxiv. @scottaubrey  can you confirm please?

**Comment by scottaubrey** [comment]
I'm not sure how well the comment above had aged, but that is an obsolete page, that we want to remove: https://github.com/elifesciences/enhanced-preprints-server/issues/432
