### ISSUE TITLE
jump menu column grows with large text

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#283]
# Description

![Image](https://user-images.githubusercontent.com/375812/184840079-f8562611-4dd4-47c7-a42d-9c2757395ccb.png)

![Image](https://user-images.githubusercontent.com/375812/184840115-9f705636-47b0-40bc-a9ef-854170761c6a.png)

It can also cause problems when the jump-menu style is updated as the higher font-weight can make the column grow causing a jump in centre content.

**Comment by QueenKraken** [comment]
Resolved by the new grid.
