### ISSUE TITLE
MSA and curation labels should support limited html such as sup and sub

### ISSUE THREAD

**Issue by nlisgo** [elifesciences/enhanced-preprints-server#301]
# Description

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] ...

**Comment by scottaubrey** [comment]
Is there a use-case you have in mind @nlisgo ? We couldn't think of a use-case at backlog review.
