### ISSUE TITLE
Static prototype updates

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/enhanced-preprints-server#304]
At request from @discodavey 

- [x] Example 1: In jump menu, please use "Peer reviews" and "Author Response" headings only. (i.e. Use Peer review instead of "Evaluation, Review 1, Review 2")
- [ ] Example 1: Fix position of jump menu to bottom of page/for reviews
- [x] Example 1: Fix left margin/spacing of dividing line in jump menu, or remove it

- [x] Example 2: Fix position of "Back to article" button and increase space above jump menu to give it space

- [x] Example 3: Update jump menu anchor/scroll position to allow for the fixed tab bar (i.e. scroll a little less far down)

- [x] Example 4: Update review tab content to match other examples (content)

- [x] All: Use "Evaluation summary" for the summary at the top of each article page (be aware of "Evaluation" in peer review content)

**Comment by chris-huggins** [comment]
Ok sounds great, thanks @discodavey. Enjoy your weekend!

**Comment by chris-huggins** [comment]
@discodavey I just noticed the "Evaluation Summary" heading has changed on the article page for each prototype. 

Can you please make sure the summary above the abstract is called "Evaluation summary" for each prototype, and that the same is shown in the jump menu. But please be aware that there is an "Evaluation" within the peer review content/page/column for each, that should remain as "Evaluation".

I've added a task to the ticket description.

**Comment by chris-huggins** [comment]
@discodavey I've also unchecked `Example 4: Update review tab content to match other examples` because I'm still seeing the old content. I'm guessing it could just be that it hasn't been deployed yet?

**Comment by discodavey** [comment]
@chris-huggins Just the jump menu to sort now on the left so is still shows on peer review and author response. @nlisgo is going to look at it this morning.

@nlisgo I have pushed the branch that I was working on into master so if you clone the master and create a new branch that will be good.

Repo is here
https://github.com/elifesciences/epp-layout-experiments
