### ISSUE TITLE
Tab content

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#396]
# Description

As an eLife reader I would like to see content when I click on the peer review and figures tab to avoid a poor user experience

### What is the benefit of solving the problem?

Provided key data in clearly defined locations
Providing an intuitive way for users to navigate

### How will we know when the problem has been solved?

The named tabs will have corresponding data contained within them

# Documents and Resources

# Tasks

# Definition of Done

- [ ] Solution deployed to a staging environment.
- [ ]

**Comment by QueenKraken** [comment]
@scottaubrey hello! Is this done for launch? Any follow up activity needed?

**Comment by scottaubrey** [comment]
Yup, this has been done.
