### ISSUE TITLE
Work with Biorxiv on a ingest mechanism for preprint XML

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#42]
After https://github.com/elifesciences/enhanced-preprints/issues/34, we need to find a new route to ingest XML data form Biorxiv

**Comment by QueenKraken** [comment]
Set up complete, awaiting items to be added in to the bucket before next steps can be taken

**Comment by QueenKraken** [comment]
@BlueReZZ is there any update on the escalation please?

**Comment by BlueReZZ** [comment]
> @BlueReZZ is there any update on the escalation please?

Nothing yet, I'm meeting with Damian on Friday morning to get the latest update but I would have expected the meetings to have happened already, so probably worth checking the bucket again later today and later tomorrow in the meantime.

**Comment by QueenKraken** [comment]
Meca files received. Scott is manually ingesting this. Still need to create an ingest mechanism. Moving ticket down priority list to revisit post announcement. BioRxiv still need to automate the Meca file delivery too.
