### ISSUE TITLE
Review and refactor code - EPP

### ISSUE THREAD

**Issue by QueenKraken** [elifesciences/enhanced-preprints-server#444]
# Description

Review and identify any code which needs refactoring post October launch
@discodavey to provide details

When the hamburger menu is selected the eLife logo jumps position - this should remain static. 
When hovering over the close x the cursor point should change.

**Comment by discodavey** [comment]
Cursor has been added in PR below:
https://github.com/elifesciences/enhanced-preprints-client/pull/192

**Comment by QueenKraken** [comment]
From @discodavey we will refactor component by component so will close this ticket.
