### ISSUE TITLE
What domain name does this need to be hosted under?

### ISSUE THREAD

**Issue by NuclearRedeye** [elifesciences/enhanced-preprints-server#6]
# Description

As per title, we need to know where this new system is going to live?

# Task
- [ ] Domain name purchased/registered for this new platform.

**Comment by Maelplaine** [comment]
@NuclearRedeye @chris-huggins What do you think?
We could use article.hosting
Or a subdomain of sciety
Or a subdomain of eLife
Or a subdomain of ColLab 
Or we could buy enhancedpreprint.org

**Comment by lsh-0** [comment]
Speaking as someone who has to maintain this sort of thing indefinitely, it would be good if whatever you choose could be [brought under configuration control](https://github.com/elifesciences/builder/blob/master/projects/elife.yaml).

**Comment by scottaubrey** [comment]
Can we come up with a better temporary name than just `epp-node-prototype`?

**Comment by Maelplaine** [comment]
@BlueReZZ Should it be subdomain of eLife like https://reviewed-preprint.elifescience.org/
Or do we want to include them in the website like this for example:
https://elifesciences.org/preprint/74443
https://elifesciences.org/reviewed-preprint/74443
I will add this question to the next cross-functional meeting

**Comment by BlueReZZ** [comment]
Definitely one to be answered by people closer to the user. My general feeling is that a subdomain is simpler technically and more semantically correct but readers may expect something different.

**Comment by Maelplaine** [comment]
Yes we should get some feedback from users. Anurag from Google Scholar recommends that the URL structure for preprints would ideally indicate them as such in an unambiguous structure.
I think a URL like using the word "preprint" like this https://elifesciences.org/preprint/74443 could be more future-proof if we want to list and display preprints under review in the future

**Comment by lsh-0** [comment]
My thoughts:

If preprints are to be a separate system from the journal then a subdomain would be best. `preprints.elifesciences.org` or some such. Things get a bit awkward when meshing disparate systems (like Lens).

If preprints are to be a separate system from the journal *initially* but will be incorporated *eventually* then something like `elifesciences.org/preprints` can be accommodated. We'd essentially divert traffic to `/preprints` to the new system. It means we wouldn't have to do redirects from `preprints.elifesciences.org/foo` to `elifesciences.org/preprints/foo` in the future. Redirects are pure technical debt and we already have a mountain of them.

If preprints are to be incorporated into the journal proper, including having XML and article JSON, living in lax etc, then it should have a URL like any other article: `elifesciences.org/articles/12345`. This was my understanding of Damian's direction, that preprints and peer-reviewed articles would be living alongside one another. (If preprints don't have a DOI then they can't have a proper `/article` URL.)

I haven't seen or heard of any activity in elife-bot, bot-lax-adaptor, lax, api-raml, production etc to accommodate preprints so I'm _guessing_ this is a bolt-on, at least for the time being.

> Anurag from Google Scholar recommends that the URL structure for preprints would ideally indicate them as such in an unambiguous structure.

Google Scholar are not transparent, their advice has been contradictory and their problems indexing journal content are often impossible to debug. It's important we ask for their stance on this but I don't think we should let them set our URL policy.

Also, an article's HTML metadata should indicate unambiguously whether it's a preprint or not. I'd be keen to know how else Google Scholar may distinguish a preprint from a peer-reviewed article as this is the sum of their public knowledge we have to go on: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

> I think a URL like using the word "preprint" like this https://elifesciences.org/preprint/74443 could be more future-proof if we want to list and display preprints under review in the future

I agree, I think an article's status of 'preprint' is more interesting and important than it's 'poa' or 'vor' status and deserving of it's own namespace in the journal, just like `/articles`, `/digests`, `/magazine` etc. It's also consistent with our current URL policy, straightforward to implement in the API (should we decide to do so), and cleanly separates preprint articles from peer-reviewed articles - a concession to the intermingling and prestige devaluation of our current article corpus. It would also satisfy Google Scholar, for what that is worth.

Damian on Friday:

> 1. Plan the transition to the full PRC workflow for the eLife journal, make an announcement in time for our 10 year anniversary and roll out in early 2023.

If you want an early 2023/first-quarter roll out of this then I think a lot of the technical ambiguities here need straightening out immediately. It seems like a long way away but it isn't.

**Comment by scottaubrey** [comment]
@Maelplaine Could we update this with the latest thoughts on this (i.e. from Google Scholar meeting)? Thanks.

**Comment by Maelplaine** [comment]
Google Scholar's recommendation regarding the URL is that we treat the two — VORs and reviewed preprints — as two different types of content so with a different URL structure. Something like this https://elifesciences.org/preprint/74443 
would work well.

Here are the meeting notes:
https://docs.google.com/document/d/16FkjZncbqWJqgv5YGMTbcXiMSZA3MMNFqamqV2pOhzs/edit

**Comment by lsh-0** [comment]
Thanks, @Maelplaine 

A few points from those meeting notes:

> because of multiple preprint versions - will need suffix for each version

I assume you mean a suffix for `/preprints/$id`, in which case [we have a precedent already](https://github.com/elifesciences/api-raml/blob/e4289c613c57a3262df05269b18c16cb1de0ba75/dist/api.raml#L479-L626) with the `/articles/$id` URL. I would recommend `/preprints/$id/versions/$version`.

>  We should change the archive to have links to each year instead of the POST select.
> We are using “Post” which isn’t great for the crawler.

There is no `POST` happening here, the screenshot proves it and you can see for yourself: https://elifesciences.org/archive/2012

And just to prove there is no JS shenanigans going on, converting that GET to a POST:
![Screenshot at 2022-08-26 09-31-08](https://user-images.githubusercontent.com/2142748/186789414-16102968-027b-45b3-a05a-c6183226c418.png)

So is Google Scholar actually indexing those pages **but with difficulty** (??) or not indexing them at all, because of the form-based navigation? 

Whatever today's excuse is, it would be easy to also provide a simple list of links that a bot a could follow, either as part of the [page's metadata](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-next) or via[ a `<nav>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), but I'd defer to @discodavey on that.

**Comment by lsh-0** [comment]
> Do we want to redirect the canonical link to the VOR? That would make this a non issue - it would always point to the newest version… surely we want to do this? 301?

I would recommend *not* doing that. Make it clear on the preprint page that it now *also* has a VOR (which may be significantly different to the most recent preprint). 

The canonical version of an article can be indicated [via the page metadata or HTTP header](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls?hl=en&visit_id=637970699015901198-3527306668&rd=1), or both.

We currently embed the canonical URL into the HTML:

![Screenshot at 2022-08-26 09-51-40](https://user-images.githubusercontent.com/2142748/186791200-5625217a-ed6b-46ae-90a5-191505c906ab.png)

And we tackled adding the HTTP header version of the canonical article to the PDF downloads in this ticket: https://github.com/elifesciences/issues/issues/5201

We would do the same with preprints that went on to gain a VOR - the canonical URL for `/preprints/$id` would point to their new `/articles/$id`.

**Comment by chris-huggins** [comment]
> I would recommend _not_ doing that. For humans, make it clear on the preprint page that it now _also_ has a VOR (which may be significantly different to the most recent preprint).

Thanks for your input on this @lsh-0. You quoted my notes from the meeting there, but I agree we with your suggestion.

**Comment by scottaubrey** [comment]
As per the [latest info from @FAtherden-eLife](https://elifesciences.slack.com/archives/C03EVJSUA77/p1663862125730359?thread_ts=1663860213.504309&cid=C03EVJSUA77), we're looking at going with `elifesciences.org/reviewed-preprints/{msid}[v{versionid}]`. 

This means, for the purposes of this ticket about the deployment domain, it doesn't really matter what "domain" our EPP platform is hosted on. The suggestion put forward at the cross-functional meeting earlier this week was to match existing convention, and match it with `epp`, so going with `prod--epp.elifesciences.org`, (or `staging--` for staging, etc). 

I will action the staging environment [part of this today](https://github.com/elifesciences/elife-flux-test/pull/504), and close this ticket. 

The path changes to EPP to match expected path on elifesciences.org will follow early next week when [another PR](https://github.com/elifesciences/enhanced-preprints-client/pull/52) gets merged and joins all the deployment bits together. We can then finally drop the badly named `epp-node-prototype` subdomain. 

Related issues:
https://github.com/elifesciences/enhanced-preprints-server/issues/366
https://github.com/elifesciences/enhanced-preprints-client/issues/54
